# logLevel
# Only print same or higher log level.
# Values: debug, info, warning, error or fatal
#
# logLevel = "debug"

# logNoColor
# Log with no color.
#
# logNoColor = true
logNoColor = true

# logNoDate
# Log with no date.
#
# logNoDate = true
logNoDate = true

# skipInterfaces
# Skip interfaces.
#
# skipInterfaces = ["lo"]

# skipDrivers
# Skip drivers.
#
# skipDrivers = ["veth", "bridge"]

# topic
# Kafka topic.
#
# topic = "ifwatch"

# brokers
# Kafka brokers.
#
# brokers = ["kafka1", "kafka2", "kafka3"]

# timeout
# Kafka connection timeout in seconds.
#
# timeout = 3

# rateLimit
# Highwater mark per interface for messages per second sent to Kafka, once reached it will send a
# stop event and not publish further messages until it drop's below the limit. Once it drops
# below the limit a resume event will be sent.
#
# rateLimit = 5

# comprAlgo
# Compression algorithm used for messages.
# Values: none, gzip, lzw, snappy, xz, zlib
#
# comprAlgo = "snappy"

# refresh
# Refresh entries in Kafka for caching every x hours, where 0 is no refresh.
#
# refresh = 24
