# logLevel
# Only print same or higher log level.
# Values: debug, info, warning, error or fatal
#
# logLevel = "debug"

# logNoColor
# Log with no color.
#
# logNoColor = true

# logNoDate
# Log with no date.
#
# logNoDate = true

# skipInterfaces
# Skip interfaces.
#
# skipInterfaces = ["lo"]

# skipDrivers
# Skip drivers.
#
# skipDrivers = ["veth", "bridge"]

# topic
# Kafka topic.
#
# topic = "ifwatch"

# brokers
# Kafka brokers.
#
# brokers = ["kafka1", "kafka2", "kafka3"]

# timeout
# Kafka connection timeout in seconds.
#
# timeout = 3
